# Generated by Django 2.1.2 on 2018-12-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('costo_pre', models.IntegerField()),
                ('costo_real', models.IntegerField()),
                ('notas', models.CharField(max_length=300)),
                ('tienda', models.ManyToManyField(to='tienda.Tiendas')),
            ],
        ),
    ]
