# Generated by Django 2.1.2 on 2018-11-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fech_nac',
            field=models.DateTimeField(),
        ),
    ]
