# Generated by Django 2.1.2 on 2018-11-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20181124_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fech_nac',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sexo',
        ),
    ]
