# Generated by Django 2.1.2 on 2018-12-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_auto_20181124_2108'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateField(auto_now_add=True)),
                ('modificada', models.DateField(auto_now=True)),
                ('total_productos', models.IntegerField(default=0)),
                ('total_productos_comprados', models.IntegerField(default=0)),
                ('costo_total_presupuestado', models.IntegerField(default=0)),
                ('costo_total_real', models.IntegerField(default=0)),
                ('productos', models.ManyToManyField(to='producto.Productos')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
