# Generated by Django 2.1.2 on 2018-12-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('sucursal', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('sitio_web', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado')], default='P', max_length=1)),
            ],
        ),
    ]
